### PR TITLE
Changed ProductID to ProductName and add support for UR10

### PR DESCRIPTION
**Pull request by DdenBraver**
- Changed xAzurePackSetup to use ProductName instead of ProductID
- Changed xAzurePackUpdate to use ProductName and ProductVersion instead of ProductID
- Update to example to remove the need for community resources
- Includes compatibility for Update Rollup 10

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xazurepack/11)

### CODE REVIEW

**Comment by DdenBraver** [comment]
Can somebody please review this pull request? :-)
@kwirkykat @TravisEz13

**Comment by TravisEz13** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1, line 63 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KMWKoPZT647-PPVBTsx:-KMWKoP_kEaHJBFhwc1G:835925671) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1#L63)):_

> ``` PowerShell
>     $TempPath = [IO.Path]::GetTempPath().TrimEnd('\')
>     $buildversion = '3.33.8196.14' # Update Rollup 10 https://support.microsoft.com/en-gb/kb/3158609
>     $Products = (Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*,
> ```

This  to get products code is repeated in several places make it a function​ for maintainability​ and testability​.  Probably in a module the resource share.

---

_[DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1, line 126 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KMWLeA4UhGyY74fEz0K:-KMWLeA4UhGyY74fEz0L:-1381205137) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1#L126)):_

> ``` PowerShell
>     $result = $true
>     $buildversion = '3.33.8196.14' # Update Rollup 10 https://support.microsoft.com/en-gb/kb/3158609
>     $Products = (Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*,
> ```

Add unit test coverage for this code to get the list of products.

---

_[DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1, line 233 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KMWLoQC7ZkRhakRZov5:-KMWLoQC7ZkRhakRZov6:-1703013903) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackUpdate/MSFT_xAzurePackUpdate.psm1#L233)):_

> ``` PowerShell
> }
> 
> function Get-WAPComponentNames
> ```

Add unit test coverage for this updated functionality.

---

_[Examples/AzurePack_splitroles_example.ps1, line 1340 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KMWLKUCGl6jCYSf5MvN:-KMWLKUCGl6jCYSf5MvO:-1418438787) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/Examples/AzurePack_splitroles_example.ps1#L1340)):_

> ``` PowerShell
>                         Location = 'LocalMachine'
>                         PsDscRunAsCredential = $Node.InstallerServiceAccount
>                         }                    
> ```

Minor, remove training spaces if you can.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xazurepack/11)_

**Comment by narrieta** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

_[DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1, line 84 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KOGllcr0jNILseXAF7k:-KOGllcr0jNILseXAF7l:-1365427694) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1#L84)):_

> ``` PowerShell
>         [System.Management.Automation.PSCredential]
>         [System.Management.Automation.Credential()]
>         $SetupCredential,
> ```

We shouldn't add the Credential attribute since it may trigger a prompt and the DSC engine does not support interactive input.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xazurepack/11)_

**Comment by narrieta** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

_[DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1, line 125 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KOGzh3rIWZJ2Tr3sZw9:-KOGzh3rIWZJ2Tr3sZwA:879586015) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1#L125)):_

> ``` PowerShell
> 
>                     $Componentnames = Get-WAPComponentNames -Component $Component
>                     # $IdentifyingNumbers = Get-WAPComponentIdentifyingNumbers -Component $Component
> ```

leftover?

---

_[DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1, line 127 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KOGzkqWt6t2I2u8LYSt:-KOGzkqWt6t2I2u8LYSu:879586015) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1#L127)):_

> ``` PowerShell
>                     # $IdentifyingNumbers = Get-WAPComponentIdentifyingNumbers -Component $Component
>                     $ComponentInstalled = Get-ComponentInstalled -Products $Products -ComponentNames $Componentnames
>                     # $ComponentInstalled = Get-ComponentInstalled -Products $Products -IdentifyingNumbers $IdentifyingNumbers
> ```

leftover?

---

_[DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1, line 235 [r1]](https://reviewable.io:443/reviews/powershell/xazurepack/11#-KOGzxXFtX1fFjjYV0me:-KOGzxXFtX1fFjjYV0mf:1197147652) ([raw file](https://github.com/powershell/xazurepack/blob/5916bae2a8adeb2b7a30bd0bb906883c3cac3e85/DSCResources/MSFT_xAzurePackSetup/MSFT_xAzurePackSetup.psm1#L235)):_

> Get-ItemProperty HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall*,
>                                           HKLM:\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall* | Where-Object {![string]::IsNullOrWhiteSpace($_.DisplayName)} | Sort-Object DisplayName -Unique).DisplayName

Can we wrap this in a function? The expression is a little complex and is used in more than 1 place

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xazurepack/11)_

**Comment by johlju** [comment]
@DdenBraver It was along time since something happened on this PR. Do you have time to work on this PR? I will label it as abandoned until I hear from you. Thanks!

**Comment by DdenBraver** [comment]
It has been a very long time indeed, and honestly I completely forgot about this PR.
I think it is best to cancel this PR, as WAP has had many updates in the meantime making this change very much outdated.

**Comment by johlju** [comment]
@DdenBraver Thanks for responding. I keep this PR open so that someone else can continue the work, or if the issue is resolved by another PR then we close this PR. I keep the 'abandoned' label so another contributor knows that they can continue the work.

**Comment by gaelcolas** [comment]
I've seen little contribution and interest for this resource module in the past few years, so I'm just going to close this off.
If someone is willing to maintain and improve this module, please get in touch.

**Pull request closed without merging**
